### ISSUE TITLE
Latest version works only for the first item

### ISSUE THREAD

**Issue by hudochenkov** [aaronsaray/feedlybackgroundtab#12]
I noticed that you've updated version and changed selector. Now extension opens only first item. Selector `.selectedEntry a.title` works, but it was removed in the latest commit.

I use Full Article view in Feedly.

**Comment by ergodicbreak** [comment]
Similar issue, I get this in the console now in latest Chrome when hitting my shortcut key, 

`Could not find any selectors from: a.visitWebsiteButton`

**Comment by aaronsaray** [comment]
Version 0.10 has been released.

I've just pushed an update that I think should fix this problem for you @hudochenkov 

For you @ergodicbreak I'm not sure what the problem is yet.  I have not been able to duplicate that issue.  With 0.10 released, can you check to see if it works for you too?

**Comment by hudochenkov** [comment]
Works like a charm! Thank you!

**Comment by ergodicbreak** [comment]
Thanks for the quick update @aaronsaray , however this doesn't work for me. The error in console is now, 

`Could not find any selectors from: .selectedEntry a.visitWebsiteButton,a.visitWebsiteButton`

When I inspect the button element the outerHTML is for example:

```
<a href="http://wozniak.ca/mainframes-as-a-lifestyle-choice" class="fx-button secondary full-width visitWebsiteButton" style="margin-top:24px" target="_blank"> 
Visit Website 
</a>
```

I use Feedly in list view (titles only).

**Comment by hudochenkov** [comment]
@ergodicbreak this is strange. `.selectedEntry a.visitWebsiteButton` selector should perfectly match button for current open article. I tried in Title Only view and it works.

**Comment by aaronsaray** [comment]
@ergodicbreak Yes please open a new issue.  Could you also capture the HTML in the elements panel using 'copy -> outer HTML' on the body and put that in the ticket? (Do this when you're finally to a place where you're viewing the article you wish to open) Please note - this will of course show us what feeds you subscribe to - so if you don't feel comfortable with this, I understand.  But I really need to see the HTML entirely so I can figure out why it's not working.
