### ISSUE TITLE
Shortcut key doesn't work in title only view when selected item is not expanded

### ISSUE THREAD

**Issue by ergodicbreak** [aaronsaray/feedlybackgroundtab#14]
Thanks to @hudochenkov I've narrowed down the issue -- the shortcut key *does* work when an item is expanded in list view (i.e. you hit the `enter` key or click on the title in title only view). It *does not* work when the item is not expanded. Prior to the update the shortcut key worked both ways. 

I've pasted the outerHTML of the body of my title only list view into a gist, https://gist.github.com/ergodicbreak/41182f2a9b18f79eeef3d8daac3acb97

For reference my normal use is to 'n' and 'p' through the title only view and hit my shortcut key when I want to open an item in a background tab. I don't usually expand the items in Feedly.

**Comment by aaronsaray** [comment]
This update is coming in a few minutes - thanks!
