### ISSUE TITLE
Could not find any selectors from: div.selectedEntry a.title,.selectedEntry a.visitWebsiteButton,a.visitWebsiteButton web-main-bundle.js:45 [feedly][reader] flushing reads:1

### ISSUE THREAD

**Issue by jkirklan** [aaronsaray/feedlybackgroundtab#16]
When I hit my open in background tab in feedly I get the following error.   

Could not find any selectors from: div.selectedEntry a.title,.selectedEntry a.visitWebsiteButton,a.visitWebsiteButton
web-main-bundle.js:45 [feedly][reader] flushing reads:1

I am running 0.11 version of the extension.

**Comment by jkirklan** [comment]
It is coming from keypress.js line 61

**Comment by aaronsaray** [comment]
What view are you using when you get this error? Title view? Card view? is anything expanded?  Do you see the 'go to website' button at the bottom?  If so, what classes does it have on it?

Thanks!

**Comment by jkirklan** [comment]
If I am in any unexpanded view  (card, title, magazine) it doesn't work.  If I open the item individually it works.   It does show visit website at the bottom of each time I am in the full article view.  Where would I view the classes?

**Comment by aaronsaray** [comment]
If you're on title view, and unexpanded, are you making sure that at least one item is selected?  for example, if you go to that view, and hit the key, none will be selected and it won't work.  Hit 'n' and the first one would be selected (you can tell because of the faint outline change), then it should work.  At least it did for me. :-/

If you are indeed making sure one is selected, can you attach a screenshot of your current view when you're having the problem? That might help me ask better questions. :) Thanks for your patience!

**Comment by jkirklan** [comment]
In title view I use j or k to highlight an item and hit my hot key does not open an article.    I hit enter and open the article and hit the hot key and the article opens in the background.  Attaching a screen shot.   

![screenshot 2016-08-31 15 27 34](https://cloud.githubusercontent.com/assets/1660733/18143316/886bf052-6f8f-11e6-860b-70596fe107e2.png)

**Comment by jkirklan** [comment]
Any updates?

**Comment by aaronsaray** [comment]
Sorry - been a bit swamped at work and at home.  Should be taking a look at this tomorrow. :)

**Comment by jkirklan** [comment]
Thanks!

**Comment by jkirklan** [comment]
I disabled all other extensions in Chrome as a test to see if another extension was interfering.   That made no difference.

**Comment by jkirklan** [comment]
Any updates?

**Comment by BrianCS** [comment]
Your layout looks slightly different from mine. I'm a free Tier-er, your screenshot shows you're Pro.

Feedly Pro + Team users are piloting a React-based rendering engine (CEO says "[rewriting feedly in React](https://plus.google.com/+PhistucKProductions/posts/amkvSMwTTDg)", so may be pretty substantial). Presumably eventually that rolls out to Free tier too. Markup is perhaps different enough to muss up that query.

**Comment by aaronsaray** [comment]
I sent a note out to them via twitter to see if I can't snag a pro version for a few days to upgrade the plugin against.  We'll see what they say.

**Comment by jkirklan** [comment]
thanks

**Comment by jkirklan** [comment]
Let me know If I can help
