### ISSUE TITLE
Collapsed entry in "title only" view

### ISSUE THREAD

**Issue by dmahr1** [aaronsaray/feedlybackgroundtab#17]
I'm having the same issue as #14: the hotkey does not work when selecting a collapsed entry in "Title Only" view. Looks like Feedly just changed their layout and the `selectedEntry` class might have been renamed `selected` but I'm not 100% sure.

**Comment by BrianCS** [comment]
Yeah I'm seeing the new React-based layout on my free-tier account, and reproducing the same non-behavior, sweet

**Comment by BrianCS** [comment]
The generated markup's verbose enough that this looks like it can be corrected by adding another selector, `.entry.selected a.title`, pull request incoming

**Comment by aaronsaray** [comment]
Thanks! I'm pushing this out now.  I even had them upgrade me to a pro account, and I still don't get the react layout... so I could never fix this :)  Please re-open if this is still a problem in a few hours.

**Comment by dmahr1** [comment]
Just tested this with the production Chrome extension and everything is working properly again! Thanks for the fast turnaround @BrianCS @aaronsaray 👍
