### ISSUE TITLE
Incorrect article being opened

### ISSUE THREAD

**Issue by skymoo** [aaronsaray/feedlybackgroundtab#8]
This afternoon I've noticed that the extension doesn't seem to be opening the correct article, as far as I can tell the article that is at the top of the current folder is opened not the current article.

**Comment by woodspock** [comment]
Same problem for me using 0.7 version

**Comment by hudochenkov** [comment]
+1

**Comment by jmaciasluque** [comment]
+1. Can I go back to 0.6 in my browser?...

**Comment by skymoo** [comment]
And this evening it seems to have started working as expected again...

**Comment by aaronsaray** [comment]
Thanks for the update.  I just released 0.8 with a fix.  Sorry about that friends!  Thanks for your patience.
