### ISSUE TITLE
Not opening tabs

### ISSUE THREAD

**Issue by skymoo** [aaronsaray/feedlybackgroundtab#9]
Today I've been having intermittent issues with the extension, sometimes it will work but most of the time it doesn't. I've been seeing this on the ChromeOS Dev Channel and on the Mac Stable Mac Channel.

**Comment by skymoo** [comment]
And this morning things seem to be working much more reliably...

**Comment by aaronsaray** [comment]
When you say much more reliably - is that 100% working again? Or are there some scenarios it's still not working?

If it's still an issue - can you describe the reading view you're using? (Ie - what buttons did you click to get to where you're seeing the problem ) or include a screenshot?  Thanks!

**Comment by skymoo** [comment]
Seems to be now, what was happening is that when I pressed the key I'd assigned to open tabs in the background nothing was happening. Reloading Feedly, clearing cache, disabling and then re-enabling the extension all resulted in no tabs being opened. Now it's working and I haven't had any tabs fail to open since shortly after reporting the issue.

**Comment by aaronsaray** [comment]
Could you tell me which key you assigned?  Once you respond, I'll close the ticket - but perhaps knowing which key you're using might help me in the future.  Thanks so much for your help!

**Comment by skymoo** [comment]
";"

**Comment by aaronsaray** [comment]
Ok thanks - I'll keep an eye out for anything else that happens like this.
